### ISSUE TITLE
Action cannot find .mdlrc

### ISSUE THREAD

**Issue by snim2** [actionshub/markdownlint#11]
## :ghost: Brief Description

This action cannot find the mdl config file, if  `.mdlrc` is in the root of the repo. I've only tested this in feature branches, so the steps below refer to that use case. This is my first time using GitHub actions, rather than Travis or GitLab CI, so possibly this is user error... :sob:

## :pancakes: Action version

[master@fc56786](https://github.com/actionshub/markdownlint/commit/fc5678687e9328d425848ceb9e80fe67ade76a99)

## :tophat: workflow configuration

```yaml
name: markdownlint
on: [pull_request]
jobs:
    markdownlint:
        runs-on: ubuntu-latest
        steps:
        - name: Check out code
          uses: actions/checkout@v2
          with:
              ref: ${{ github.event.pull_request.head.sha }}
        - name: Run mdl
          uses: actionshub/markdownlint@master
```

## Steps To Reproduce

1. Create a new, blank repo containing a Markdown file with some very long lines 
1. Enable third party actions on the new repo. 
1. Create a pull request and add the above workflow and this `.mdlrc` file in the root of the repo:
```
# All rules on by default.
all
# Extend line length.
rule 'MD013', :line_length => 99999
# Allow multiple headers with same content.
exclude_rule 'MD024'
```

The action will complain about overlong lines (violations of `MD013`).

## :police_car: Expected behavior

Given all the above, the action should pass on the feature branch.

## :heavy_plus_sign: Additional context

Related to #7 which was resolved by adding some docs to the `README` in this repo. :scroll:
