### ISSUE TITLE
filesToIgnoreRegex doesn't seem to work

### ISSUE THREAD

**Issue by jaymzh** [actionshub/markdownlint#15]
## :ghost: Brief Description

`filesToIgnoreRegex` doesn't seem to work.

## :pancakes: Action version

1.2.2

## :tophat: workflow configuration

```yaml
jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Lint Markdown
      uses: actionshub/markdownlint@1.2.2
      with:
        filesToIgnoreRegex: '((test|example|bin)/.*|doc/RULES.md)'
```

The RE does match:

```shell
$ echo test/rule_tests/lists_without_blank_lines.md | grep -oE '((test|example|bin)/.*|doc/RULES.md)'
test/rule_tests/lists_without_blank_lines.md
```

## Steps To Reproduce

1. Create file called `test/rule_tests/lists_without_blank_lines.md`
2. add config like above

You can see this in [this test](https://github.com/markdownlint/markdownlint/pull/370/checks?check_run_id=1804880139) where that file (and many other like it) get matched.

## :police_car: Expected behavior

It ignores the file.
