### ISSUE TITLE
mdl action finds non-md files

### ISSUE THREAD

**Issue by jaymzh** [actionshub/markdownlint#16]
## :ghost: Brief Description

the mdl action seems to (possibly only when `filesToIgnoreRegex` is set?) find non-Markdown files (specifically, in this case, ruby files) and lint them (which obviously won't work).

## :pancakes: Action version

1.2.2

## :tophat: workflow configuration

```
  markdown:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Lint Markdown
      uses: actionshub/markdownlint@1.2.2
      with:
        filesToIgnoreRegex: '((test|example|bin)/.*|doc/RULES.md)'
```

## Steps To Reproduce

1. Use above config
2. have a ruby file
3. see it fail on ruby files

Ex: [this test](https://github.com/markdownlint/markdownlint/pull/370/checks?check_run_id=1811822842)

## :police_car: Expected behavior

It does not try to lint Ruby files.

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by Xorima** [comment]
One small bug mate is your regex isn't escaped and your rules are in doc**s** not doc

```
  markdown:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Lint Markdown
      uses: actionshub/markdownlint@invert-match
      with:
        filesToIgnoreRegex: '((test|example|bin)\/.*|doc\/RULES.md)'
```

I have also merged in a fix for this so let me know if it is still an issue :)
