### ISSUE TITLE
run limited set of rules / exclude rules

### ISSUE THREAD

**Issue by wopian** [actionshub/markdownlint#7]
## 😦  Problem Statement

(GitHub doesn't have `:person_frowning:` as a shortcode for 🙍)

Right now this action runs mdl with all the lint rules active. 

I maintain a project that has multilingual README/CONTRIBUTING files that contain right-to-left languages, which require HTML tags along with assembly code examples that conflict with spacing rules. As it stands there is no way to disable these lint rules from being run.

## :grey_question: Possible Solution

Matching mdl's behaviour:
- If rules are defined, only those rules are run (e.g `mdl --rules MD001` only checks `MD001`)
- If rules are prefixed with `~`, those rules are excluded (`mdl --rules ~MD001` checks every rule except `MD001`)

The following configuration would call `mdl --rules ~MD001,~MD002`:

```yaml
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Run mdl
      uses: actionshub/markdownlint@master
      with:
        rules: ~MD001,~MD002
```

## :heavy_plus_sign: Additional context

I currently have a fork with the rules I need disabled hardcoded in the entrypoint.sh at https://github.com/wopian/markdownlint
